#!/bin/bash

if [ -e $(cat .config/moz_tree)/dist/universal/firefox/NightlyDebug.app/Contents/MacOS/firefox ]
then
  echo "Universal Debug"
  $(cat .config/moz_tree)/dist/universal/firefox/NightlyDebug.app/Contents/MacOS/firefox -P "Minefield3" -no-remote $@
  exit
fi

if [ -e $(cat .config/moz_tree)/dist/universal/firefox/Nightly.app/Contents/MacOS/firefox ]
then
  echo "Universal Opt"
  $(cat .config/moz_tree)/dist/universal/firefox/Nightly.app/Contents/MacOS/firefox -P "Minefield3" -no-remote $@
  exit
fi

if [ -e $(cat .config/moz_tree)/dist/NightlyDebug.app/Contents/MacOS/firefox ]
then
  echo "Debug"
  $(cat .config/moz_tree)/dist/NightlyDebug.app/Contents/MacOS/firefox -P "Minefield3" -no-remote $@
  exit
fi

if [ -e $(cat .config/moz_tree)/dist/Nightly.app/Contents/MacOS/firefox ]
then
  echo $(cat .config/moz_tree)
  echo "Opt"
  $(cat .config/moz_tree)/dist/Nightly.app/Contents/MacOS/firefox -P "Minefield3" -no-remote $@
  exit
fi

if [ -e $(cat .config/moz_tree)/dist/bin/firefox ]
then
  echo $(cat .config/moz_tree)
  $(cat .config/moz_tree)/dist/bin/firefox -P "Minefield3" -no-remote $@
  exit
fi
